FROM python:3.8-slim-buster

WORKDIR /code
ENV SRC_DATEIO="src-dateio"
ENV SRC_GITHUB="src-github"
ENV LONDISTE="londiste-3.8.1"
ENV PGQ="pgq-3.5.1"
ENV SKYTOOLS="skytools-3.7.3"

RUN pip3 install 'psycopg2-binary==2.8.6' 'pyyaml==5.3.1' 'pgq==3.5' 'skytools==3.7.3' 'urllib3==1.26.7' 'requests==2.26.0' 'pyaml==21.8.3' 'poster3==0.8.1'

# ==== customized poster3 ====
COPY ${SRC_DATEIO}/poster3 /usr/local/lib/python3.8/site-packages/poster3
RUN find /usr/local/lib/python3.8/site-packages/poster3 -name "*.pyc" -type f -delete

RUN set -ex; \
    apt="apt-get -qq -y --no-install-recommends"; \
    ${apt} update -y; \
    ${apt} install wget lsb-release supervisor mc nano htop iputils-ping curl tzdata; \
    apt-get clean;  \
    rm -rf /var/lib/apt/lists/*;

# ==== londiste ====
COPY ${SRC_GITHUB}/${LONDISTE} .
COPY ${SRC_DATEIO}/${LONDISTE} ./londiste
RUN pip3 install .

# ==== pgq ====
COPY ${SRC_DATEIO}/${PGQ}/. /usr/local/lib/python3.8/site-packages/pgq
RUN find /usr/local/lib/python3.8/site-packages/pgq -name "*.pyc" -type f -delete

# ==== skytools ====
COPY ${SRC_DATEIO}/${SKYTOOLS}/. /usr/local/lib/python3.8/site-packages/skytools
RUN find /usr/local/lib/python3.8/site-packages/skytools -name "*.pyc" -type f -delete

WORKDIR /opt/londiste

CMD ["/usr/bin/supervisord", "-n"]
