FROM python:3.8-slim-buster

WORKDIR /code

RUN pip3 install 'psycopg2-binary==2.8.6' 'pyyaml==5.3.1' 'pgq==3.5' 'skytools==3.7.3' 'urllib3==1.26.7' 'requests==2.26.0' 'pyaml==21.8.3' 'poster3==0.8.1'

# ==== postgres ====
ENV DEBIAN_FRONTEND="noninteractive"
ENV PG=12
RUN set -ex; \
    apt="apt-get -qq -y --no-install-recommends"; \
	${apt} update; \
	${apt} install wget gnupg2 lsb-release git make gcc htop mc nano; \
	${apt} dist-upgrade; \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -; \
    echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main ${PG}" |  \
    tee /etc/apt/sources.list.d/pgdg.list; \
    ${apt} update; \
    # disable new cluster creation
    mkdir -p /etc/postgresql-common/createcluster.d; \
    echo "create_main_cluster = false" | tee /etc/postgresql-common/createcluster.d/no-main.conf; \
    ${apt} install postgresql-${PG} postgresql-server-dev-${PG} pgqd;

ENV PATH="/usr/lib/postgresql/${PG}/bin:${PATH}"
ENV PGHOST="/tmp"

# ==== pgq ====
RUN set -ex; \
    git clone -q --depth 1 --branch v3.4.2 https://github.com/pgq/pgq;
RUN make -C pgq; bash -c "PATH='${PATH}' make install -C pgq";

# ==== pgq-node =====
RUN set -ex; \
    git clone -q --depth 1 https://github.com/pgq/pgq-node; cd pgq-node; git -q checkout 1643a937561d0f64a73f5fcf2f63040c417fe49c; cd ..;
RUN make -C pgq-node; bash -c "PATH='${PATH}' make install -C pgq-node";


# ==== londiste-sql ====
RUN set -ex; \
    git clone -q --depth 1 https://github.com/pgq/londiste-sql; cd londiste-sql; git -q checkout ea9d037ab5a7b128370957adb055d79822bf240f; cd ..;
RUN make -C londiste-sql; bash -c "PATH='${PATH}' make install -C londiste-sql";

# ==== customized poster3 ====
RUN set -ex; \
    git clone -q --depth 1 https://github.com/gargii/python-poster3-fix;
RUN cp python-poster3-fix/* /usr/local/lib/python3.8/site-packages/poster3
RUN find /usr/local/lib/python3.8/site-packages/poster3 -name "*.pyc" -type f -delete

# ==== londiste ====
COPY . .
RUN pip3 install .

# ==== python-pgq ====
RUN set -ex; \
    git clone -q --depth 1 https://github.com/gargii/python-pgq;
RUN cp -r python-pgq//pgq/* /usr/local/lib/python3.8/site-packages/pgq
RUN find /usr/local/lib/python3.8/site-packages/pgq -name "*.pyc" -type f -delete

# ==== skytools ====
RUN set -ex; \
    git clone -q --depth 1 https://github.com/gargii/python-skytools;
RUN cp python-skytools/skytools/* /usr/local/lib/python3.8/site-packages/skytools
RUN find /usr/local/lib/python3.8/site-packages/skytools -name "*.pyc" -type f -delete


# ==== permissions & configs ====
RUN set -ex; \
    chown -R postgres:postgres "."; \
    chmod -R u+rwX,g-rwx,o-rwx ".";

USER postgres

RUN set -ex; \
    rm -rf data log; \
    mkdir -p log; \
    LANG=C initdb data; \
    sed -ri -e "s,^[# ]*(unix_socket_directories).*,\\1='/tmp'," data/postgresql.conf;

ENTRYPOINT ["tests/docker_run.sh"]
